ERROR(BS_Error_NoError,           "No error")
ERROR(BS_Error_InvalidCharacter,  "Invalid character")
ERROR(BS_Error_UnexpectedEOL,     "Unexpected End of Line")
ERROR(BS_Error_UnexpectedEOF,     "Unexpected End of File")
ERROR(BS_Error_NotFound,          "Undefined variable")