void menubtn_start();
void menubtn_select_file();
void menubtn_settings();
void menubtn_quit();
void menubtn_file_copy();
void menubtn_file_erase();
void menubtn_file_cancel();
void menubtn_back();
void menudyn_file_buttons();